server:
  port: 8083
# 默认单机配置
eureka:
  server:
    enableSelfPreservation: false
    # 清理无效节点的时间间隔，默认60秒，开发环境建议设置偏小值
    evictionIntervalTimerInMs: 10000
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/