########################################################
# 配置中心服务默认端口
########################################################
server.port: 8081

spring:
  application:
    name: yuan-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yuanxiaolong/config-test.git
          searchPaths:
          username: 604159949@qq.com
          password: 123456
        default-label: master
########################################################
### Eureka 注册中心配置
########################################################
eureka:
  instance:
    #是否优先使用IP地址作为主机名的标识
    preferIpAddress: true
    #客户端向服务端发送心跳的间隔时间，默认为30秒
    leaseRenewalIntervalInSeconds: 10
    #服务端在收到最后最后一次心跳之后的等待时间上限，超过该时间将被剔除，默认为90秒
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      #注册中心默认地址
      defaultZone: http://127.0.0.1:8083/eureka/
    #从注册中心获取信息的间隔时间 默认为30秒（本地开发建议配置较小值）
    registryFetchIntervalSeconds: 30
    #更新实例信息变化到注册中心的时间间隔，默认为30秒
    instanceInfoReplicationIntervalSeconds: 30
    #初始化实例信息到注册中心时间间隔，默认为40秒
    initialInstanceInfoReplicationIntervalSeconds: 40